import { createHash } from "node:crypto"

import { type NextFunction, type Request, type Response } from "express"
import { UAParser } from "ua-parser-js"

import type {
	DeviceFingerprint,
	DeviceInfo,
} from "../types/deviceFingerprint.js"
import { logger } from "../utils/logger.js"

function getClientIp(req: Request): string {
	const forwarded = req.headers["x-forwarded-for"]

	if (forwarded) {
		if (Array.isArray(forwarded)) {
			const firstIp = forwarded[0]
			if (firstIp && typeof firstIp === "string") {
				const parts = firstIp.split(",")
				return parts[0]?.trim() ?? firstIp.trim()
			}
		} else if (typeof forwarded === "string") {
			const parts = forwarded.split(",")
			return parts[0]?.trim() ?? forwarded.trim()
		}
	}

	return (
		(req.headers["x-real-ip"] as string | undefined) ||
		req.socket?.remoteAddress ||
		(typeof req.ip === "string" ? req.ip : undefined) ||
		"unknown"
	)
}

/**
 * Device Fingerprinting Middleware
 *
 * This middleware uses the device fingerprint generated by FingerprintJS on the client side
 * as the primary device identifier. IP address and other server-side information are stored
 * separately for analytics and security purposes, but are NOT combined into the fingerprint hash.
 *
 * How it works:
 * 1. Receives the FingerprintJS visitor ID from the X-Device-Fingerprint header (client-side)
 * 2. Uses the FingerprintJS visitor ID directly as the fingerprintHash (it's already a stable hash)
 * 3. Extracts IP address from the request (stored separately for analytics/security)
 * 4. Parses the User-Agent header to get browser and OS information (for deviceInfo)
 * 5. Stores both the hash and detailed info in req.deviceFingerprint
 *
 * Why NOT combine IP with fingerprint:
 * - FingerprintJS visitor ID is already stable across network changes
 * - Combining with IP would create different fingerprints when users switch networks/VPNs
 * - The same device would appear as multiple different devices
 * - IP is stored separately in deviceInfo for geolocation and security analysis
 *
 * Use cases:
 * - Track devices for security (detect suspicious logins from new devices)
 * - Analytics (understand what devices/browsers users are using)
 * - Fraud prevention (identify patterns in device usage)
 *
 * Note: The client-side fingerprint from FingerprintJS is much more accurate and
 * detailed than server-side header parsing alone. It includes canvas, WebGL, audio,
 * and other browser fingerprinting techniques.
 */
export const deviceFingerprintMiddleware = (
	req: Request,
	_res: Response,
	next: NextFunction
) => {
	try {
		const clientFingerprintHeader =
			req.headers["x-device-fingerprint"] || req.headers["X-Device-Fingerprint"]
		const clientFingerprint =
			typeof clientFingerprintHeader === "string"
				? clientFingerprintHeader
				: Array.isArray(clientFingerprintHeader)
					? clientFingerprintHeader[0]
					: undefined

		const ip = getClientIp(req)

		const userAgentString = req.headers["user-agent"] || ""
		const parser = new UAParser(userAgentString)
		const uaResult = parser.getResult()

		const browserName = uaResult.browser?.name
		const browserVersion = uaResult.browser?.version
		const osName = uaResult.os?.name
		const osVersion = uaResult.os?.version

		let deviceType = uaResult.device?.type
		if (!deviceType) {
			if (osName === "iOS" || osName === "Android") {
				deviceType = "mobile"
			} else {
				deviceType = "desktop"
			}
		}

		const acceptLanguage = req.headers["accept-language"]
		const acceptEncoding = req.headers["accept-encoding"]

		const deviceInfo: DeviceInfo = {
			ip,
			clientFingerprint,
			browserName: browserName ?? undefined,
			browserVersion: browserVersion ?? undefined,
			osName: osName ?? undefined,
			osVersion: osVersion ?? undefined,
			deviceType: deviceType ?? undefined,
			acceptLanguage:
				typeof acceptLanguage === "string" ? acceptLanguage : undefined,
			acceptEncoding:
				typeof acceptEncoding === "string" ? acceptEncoding : undefined,
		}

		const fingerprintHash = clientFingerprint
			? clientFingerprint
			: createHash("sha256").update(ip).digest("hex")

		const deviceFingerprint: DeviceFingerprint = {
			fingerprintHash,
			deviceInfo,
			createdAt: new Date(),
		}

		req.deviceFingerprint = deviceFingerprint

		logger.debug("Device fingerprint created", {
			fingerprintHash,
			ip,
			hasClientFingerprint: !!clientFingerprint,
			browserName,
			osName,
			deviceType,
		})

		next()
	} catch (error) {
		logger.error("Error creating device fingerprint", {
			error: error instanceof Error ? error.message : "Unknown error",
			url: req.originalUrl,
		})
		next()
	}
}
